### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by i-norden** [vulcanize/eth-statediff-service#119]
After #118 was merged, this repo will no longer build with `go build` on MacOS Apple M1 Ventura 13.0 

fails with the error:

```
cmd/util.go:35:62: cannot use db (variable of type "github.com/ethereum/go-ethereum/statediff/indexer/database/sql".Database) as type prom.DBStatsGetter in argument to prom.RegisterDBCollector:
	"github.com/ethereum/go-ethereum/statediff/indexer/database/sql".Database does not implement prom.DBStatsGetter (missing DbStats method)
```

It does not appear to be specific to my macOS env because the build was also failing in the CICD test on the merged PR: https://github.com/cerc-io/eth-statediff-service/actions/runs/4410175741/jobs/7727363550

**Comment by erikdies** [comment]
@ABastionOfSanity this PR looks like it was failing tests, hadn't been reviewed, and was then merged.  I need a post mortem or to understand what I'm missing.

**Comment by ABastionOfSanity** [comment]
@erikdies @i-norden Something is a bit off with the PR tests not running until the merge is actually done, rather than ahead of.  The github UI during the PR does not show any checks.  
When I caught this during the next step, I backed out the release and corrected.

**Comment by ABastionOfSanity** [comment]
https://github.com/vulcanize/gap-filler/blob/main/.github/workflows/on-pr-publish.yml
Is also running the checks ON merge instead of before.

**Comment by i-norden** [comment]
They run on PR: https://github.com/cerc-io/eth-statediff-service/blob/v4/.github/workflows/on-publish-pr.yml#L5

As do our other repos, including the one you linked: 
https://github.com/vulcanize/gap-filler/blob/main/.github/workflows/on-pr-publish.yml#L5
https://github.com/cerc-io/ipld-eth-server/blob/v4/.github/workflows/on-pr-publish.yaml#L5

Can also see that they have ran in the unmerged PRs that are still open: https://github.com/cerc-io/eth-statediff-service/pull/113

"When I caught this during the next step, I backed out the release and corrected."

What do you mean by this? This issue was opened yesterday by me, and nothing had been rolled back when I opened it. The fix was merged 50 minutes ago.

**Comment by i-norden** [comment]
If there is something wrong with the github actions such that they are no longer running on PR as the .yaml file specifies, then please open an issue to have this fixed. Thanks!

**Comment by i-norden** [comment]
Still not clear what the github actions issue was, no documentation was provided and all evidence suggests there was nothing wrong with the github actions. They are running on PR as expected.
