### ISSUE TITLE
Write directly to Postgres

### ISSUE THREAD

**Issue by i-norden** [vulcanize/eth-statediff-service#15]
To avoid the rate limiting issues we are experiencing by proceeding through the go-ethereum RPC server interfaces (e.g. EOFs) we should have an option to write statediffs directly to Postgres, directly analogous to https://github.com/vulcanize/go-ethereum/pull/30

We should be able to operate it in two modes:
1) Load the desired ranges from the .toml params, index statediffs from LevelDB directly into Postgres for the blocks in those ranges, and exit
2) Service runs indefinitely, awaiting RPC calls which tell it which historical blocks for which to index statediffs from LevelDB directly into Postgres

**Comment by i-norden** [comment]
More info in #11

**Comment by roysc** [comment]
Do we want to be able to specify multiple ranges in the config? Or just start/stop like for `resync`?

**Comment by i-norden** [comment]
@roysc sorry for missing that, ideally we would be able to specify multiple ranges but starting with a single start/stop is fine for now

**Comment by roysc** [comment]
No worries - this implementation does work with multiple ranges
