### ISSUE TITLE
http server only start when --log-level=debug

### ISSUE THREAD

**Issue by AFDudley** [vulcanize/eth-statediff-service#3]

**Comment by i-norden** [comment]
Running of the server is unaffected by the log level, but the message that specifies startup of the http server [was at the debug level](https://github.com/vulcanize/eth-statediff-service/blob/master/cmd/serve.go#L126), at the info level there was only the [generic rpc msg](https://github.com/vulcanize/eth-statediff-service/blob/master/cmd/serve.go#L81). Moved that ipc/http message up to the info level.
