### ISSUE TITLE
Statediff processing for missing blocks

### ISSUE THREAD

**Issue by ashwinphatak** [vulcanize/eth-statediff-service#81]
On block misses (due to gaps in the core data), the watchers make an upstream call to ipld-eth-server to write out the statediff for the missing block. Currently, ipld-eth-server calls geth to perform the statediffing. This process takes about ~40s (near the uniswap start range). 

We need to speed this process up by farming the request(s) out to a cluster of eth-statediff-service nodes.

**Comment by i-norden** [comment]
Related: https://github.com/vulcanize/ipld-eth-server/issues/130

**Comment by i-norden** [comment]
I think the problem here is more-so that the geth node that we call out to is already hammered with performing statediffing at the head of the chain, so a good first step would be to call out to a single standalone eth-statediff-service
